name: Build Electron

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Build Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update && sudo apt install libudev-dev libusb-1.0-0-dev
          npm i
          npm run deploy-linux
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - name: Build Macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install libusb-compat
          npm i
          PYTHON_PATH=$(which python) npm run deploy-mac
        env:
          GH_TOKEN: ${{ secrets.github_token }}
      - name: Build Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          npm i
          npm run deploy-win
        env:
          GH_TOKEN: ${{ secrets.github_token }}